// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $pokemon_name_ from "./routes/pokemon/[name].tsx";
import * as $PokemonItem from "./islands/PokemonItem.tsx";
import * as $Pokemones from "./islands/Pokemones.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/pokemon/[name].tsx": $pokemon_name_,
  },
  islands: {
    "./islands/PokemonItem.tsx": $PokemonItem,
    "./islands/Pokemones.tsx": $Pokemones,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
